name: dreamer4
channels:
  - conda-forge
  - defaults
dependencies:
  - glew=2.1.0
  - glib=2.86.0
  - pip=25.2
  - python=3.10
  - pip:
    - dm-control==1.0.34
    - glfw==2.10.0
    - gymnasium==0.29.1
    - gymnasium[atari,accept-rom-license]
    - gymnasium[box2d]
    - gpustat==1.1.1
    - ffmpeg==1.4
    - imageio==2.37.0
    - imageio-ffmpeg==0.6.0
    - h5py==3.14.0
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - submitit==1.5.3
    - omegaconf==2.3.0
    - git+https://github.com/nicklashansen/metaworld.git
    - mani_skill-nightly==2025.9.19.39
    - moviepy==1.0.3
    - mujoco==3.3.6
    - numpy==1.24.4
    - robodesk==1.0.0
    - ogbench==1.1.5
    - swig==4.3.1
    - tensordict==0.10.0
    - torch==2.8.0
    - torchvision==0.23.0
    - torchrl==0.10.0
    - transformers==4.56.2
    - kornia==0.8.1
    - termcolor==3.1.0
    - tqdm==4.67.1
    - wandb==0.22.1
