name: dreamer4
channels:
  - conda-forge
  - defaults
dependencies:
  - glew=2.1.0
  - glib=2.86.0
  - pip=25.2
  - python=3.10
  - pip:
    - aiohttp==3.13.3
    - pillow==12.0.0
    - glfw==2.10.0
    - gpustat==1.1.1
    - lpips==0.1.4
    - numpy==1.24.4
    - tensordict==0.10.0
    - torch==2.8.0
    - torchvision==0.23.0
    - torchrl==0.10.0
    - transformers==4.56.2
    - wandb==0.22.1
